on: [push, pull_request]

name: Continuous integration

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rust-src, rustfmt
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: nightly
          override: false
          components: rust-src, clippy
      - uses: Swatinem/rust-cache@v1
      # args: -- -D warnings
      - run: cargo clippy

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: nightly
          override: true
      - uses: Swatinem/rust-cache@v1
      - run: cargo +stable check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: nightly-2021-09-30
          override: true
      - run: cargo +stable test --workspace

  benchmarks:
    name: Runtime Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: nightly-2021-09-30
          override: true
      - run: cargo +stable build --features runtime-benchmarks

  all-ci:
    # This dummy job depends on all the mandatory checks.
    # It succeeds if and only if all checks are successful.
    needs: [fmt, clippy, check, test, benchmarks]
    runs-on: ubuntu-latest
    steps:
     - run: echo Success
